name: Build Android APK

on:
  push:
    branches:
      - main
      - development
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies
        run: npm install

      - name: Get app version
        id: app_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=v$VERSION" >> $GITHUB_OUTPUT

      - name: Expo Prebuild
        run: npx expo prebuild --platform android

      - name: Build APK with Gradle
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Prepare APK Asset
        run: |
          cp android/app/build/outputs/apk/release/app-release.apk "AudioEcho-${{ steps.app_version.outputs.version }}.apk"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        with:
          tag_name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || steps.app_version.outputs.version }}
          name: Release ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || steps.app_version.outputs.version }}
          files: |
            AudioEcho-${{ steps.app_version.outputs.version }}.apk
            android/app/build/outputs/apk/release/app-release.apk
          generate_release_notes: true
          draft: false
          prerelease: false